on: [push, pull_request, workflow_dispatch]

jobs:
  draw:
    uses: thomasdobber/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
